# Generated by Django 4.0.4 on 2022-05-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['-created_at'], 'verbose_name': 'Зап. Части', 'verbose_name_plural': 'Зап. части'},
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.CharField(default='Цена не указана', max_length=20, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
