# Generated by Django 4.0.4 on 2022-05-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_options_cars_price_alter_cars_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('order_status', models.BooleanField(default=False, verbose_name='Статус заказа')),
            ],
        ),
    ]
